# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sidekick < Formula
  desc "Oh, that's my dumb friend"
  homepage "https://github.com/jenish-jain/sidekick"
  version "2.1.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jenish-jain/sidekick/archive/refs/tags/v2.1.1/sidekick_2.1.1_darwin_amd64.tar.gz"
      sha256 "a8f96853ff939dc35df0c32d079e151d2e7b1e431fd3dbd9ccc263bc89286edb"

      def install
        bin.install "sidekick"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jenish-jain/sidekick/archive/refs/tags/v2.1.1/sidekick_2.1.1_darwin_arm64.tar.gz"
      sha256 "d6c1d0fe96166bac4bcccc0cfe679bb9c73596fca06a9dcf3f0718aa93f2c3c3"

      def install
        bin.install "sidekick"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jenish-jain/sidekick/archive/refs/tags/v2.1.1/sidekick_2.1.1_linux_arm64.tar.gz"
      sha256 "4a9c04f921c2178d95ca0c526d6c9cf8f5364c12be3ef1ad516e2621966f88c5"

      def install
        bin.install "sidekick"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/jenish-jain/sidekick/archive/refs/tags/v2.1.1/sidekick_2.1.1_linux_amd64.tar.gz"
      sha256 "1728bf21fe543ed53460387931d13037793970ef9337dfdc4c2cfc7795bceca0"

      def install
        bin.install "sidekick"
      end
    end
  end
end
