# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sidekick < Formula
  desc "Oh, that's my dumb friend"
  homepage "https://github.com/jenish-jain/sidekick"
  version "2.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jenish-jain/sidekick/archive/refs/tags/v2.1.0/sidekick_2.1.0_darwin_amd64.tar.gz"
      sha256 "4283439000155181d12534cb64ba0de3fea51c07855e222f166cd1e446887320"

      def install
        bin.install "sidekick"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jenish-jain/sidekick/archive/refs/tags/v2.1.0/sidekick_2.1.0_darwin_arm64.tar.gz"
      sha256 "b8ab3ddabf281af67ddd30318501143fcad3a29702d6ae9c36c9a857cc17c74a"

      def install
        bin.install "sidekick"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/jenish-jain/sidekick/archive/refs/tags/v2.1.0/sidekick_2.1.0_linux_amd64.tar.gz"
      sha256 "4366934d4a222f91fcca47a2b270face1ed891ca487b808a07824d9710db9dc3"

      def install
        bin.install "sidekick"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jenish-jain/sidekick/archive/refs/tags/v2.1.0/sidekick_2.1.0_linux_arm64.tar.gz"
      sha256 "692af23894d370ba442526ca65931c74d046373c5b741fb4ee66d9982f6e190f"

      def install
        bin.install "sidekick"
      end
    end
  end
end
